server:
  port: 8005

spring:
  # 数据源使用druid
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:118.31.38.245}:${MYSQL_PORT:3309}/upms?useUnicode=true&characterEncoding=UTF8
    username: jtbao
    password: jtbaodev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 7
    host: 118.31.38.245
    password: 123456
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-idle: 200
        max-active: 2000
        max-wait: 1000
