#服务端口
server:
  port: 8001

#spring配置
spring:
  #json时间显示
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  # 数据源使用druid
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:118.31.38.245}:${MYSQL_PORT:3309}/upms?useUnicode=true&characterEncoding=UTF8
    username: jtbao
    password: jtbaodev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # rabbitmq数据总线
  rabbitmq:
    virtual-host: my_vhost
    host: 47.96.167.161
    port: 5672
    username: admin
    password: admin
  # 服务追踪
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0
  zipkin:
#    base-url: http://localhost:9411/
    enabled: true
    sender:
      type: rabbit
#日志配置
logging:
  level:
    com.kyrioscraft.cloud.upmsserver: DEBUG

#通用mapper配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*/*.xml
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  identity: MYSQL
  not-empty: true

# 配置swagger
swagger:
  enabled: true
  base-package: com.kyrioscraft.cloud.upmsserver
  title: upms-server
  version: 1.0
  description: 管理后端服务
  contact:
    name: admin
